import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import SessionProvider from "~/app/_components/session-provider";
import {getServerAuthSession} from "~/server/auth";
import Navbar from "~/app/_components/navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await  getServerAuthSession()
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
      <SessionProvider session={session}>
        <TRPCReactProvider>
          <Navbar />{children}</TRPCReactProvider>
      </SessionProvider>
      </body>
    </html>
  );
}
